### ISSUE TITLE
Crash While Using RPG on 1558 thermos Server

### ISSUE THREAD

**Issue by voidswrath** [KILLER-CHIEF/KC-Weapon-Mod#1]
https://pastebin.com/J3d4J9p0

**Comment by KILLER-CHIEF** [comment]
What version of KCWM do you have installed? Thought I fixed that one a while back.

Edit: Derp the version info's in the log... never mind.

Edit 2: Okay, I see the problem. Looks like I might have to come back and make a bug fix update haha. Man it's been a while. Thanks. I'll try my best to find time to make the fix and other improvements...

**Comment by voidswrath** [comment]
<3 thanks man. We were using it in this video love the mod (pikalus clearly doesn't know how to use it lol)

Also quick suggestion instead of forcing a key bind for reloading. Maybe leave that for forcing a reload and allow a trigger to happen when you are trying to shoot the gun to reload automatically if the ammo is in your inventory. Struggles of using it in gameplay and for new users. 

https://www.youtube.com/watch?v=XIHnIxC4PMw

**Comment by KILLER-CHIEF** [comment]
Alright, thanks. I'll definitely do that if i ever make headway on the mod again (of which i can't guarantee anytime soon). Among that I wanted to fix the shoot delays to sync much better. I'll make this bug fix a priority like i said when i find the time. It's great to see people are still using the mod haha!

**Comment by KILLER-CHIEF** [comment]
Been working on it today. The bug should be fixed. Stand-by for a few more weeks till the update drops.

**Comment by voidswrath** [comment]
your the best thanks man. Keep it up <3
